image: docker:latest

services:
  - docker:dind

stages:
  - build
  - deploy

build:
  stage: build
  only:
    - master
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE/galaktika:latest ./services/galaktika
    - docker push $CI_REGISTRY_IMAGE/galaktika:latest
    - docker build -t $CI_REGISTRY_IMAGE/telegram-bot:latest ./services/telegram-bot
    - docker push $CI_REGISTRY_IMAGE/telegram-bot:latest

deploy:
  stage: deploy
  only:
    - master
  image: alpine:latest
  script:
    - apk update && apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" > ~/key && chmod 600 ~/key
    - ssh-add ~/key
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - ssh $SERVER_USER@$SERVER_IP "cd /root/cinema && docker-compose down"
    - scp docker-compose.yml $SERVER_USER@$SERVER_IP:/root/cinema/
    - ssh $SERVER_USER@$SERVER_IP "cd /root/cinema && docker-compose pull && docker-compose up -d"
