image: docker:latest

services:
  - docker:dind

stages:
  - build

build:
  stage: build
  only:
    - master
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE/cinema-galaktika:latest ./services/cinema-galaktika
    - docker push $CI_REGISTRY_IMAGE/cinema-galaktika:latest
    - docker build -t $CI_REGISTRY_IMAGE/kremen-cinema-bot:latest ./services/kremen-cinema-bot
    - docker push $CI_REGISTRY_IMAGE/kremen-cinema-bot:latest
