version: '2'

services:

  kremen-cinema-bot:
    image: registry.smartapp.com.ua/iq-hub/kremen-cinema/kremen-cinema-bot:latest
    container_name: 'kremen-cinema-bot'
    hostname: 'kremen-cinema-bot'
    restart: always
    environment:
      - KREMEN_CINEMA_BOT_TOKEN
      - KREMEN_CINEMA_BOT_ADMIN
    depends_on:
      - redis

  redis:
    image: redis:alpine
    restart: always
