version: '2'

services:

  galaktika:
    image: registry.smartapp.com.ua/pet/cinema/galaktika:latest
    build: ./services/galaktika

  telegram-bot:
    image: registry.smartapp.com.ua/pet/cinema/telegram-bot:latest
    build: ./services/telegram-bot
