service:
  name: kremen-cinema

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10

functions:
  galaxy:
    handler: cinemas.galaxy
    events:
      - http:
          method: get
          path: cinemas/galaxy
      - http:
          method: get
          path: bot/handler
