service:
  name: kremen-cinema

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    BOT_TOKEN: '536233288:AAEWievJGXdnU18SVeehwZs9S35iRqRyOic'
    CACHE_ENABLED: 'false'

functions:
  cinemas:
    handler: cinemas.galaxy
    events:
      - http:
          method: get
          path: cinemas/galaxy
  bot:
    handler: bot.handler
    events:
      - http:
          method: post
          path: bot/handler
          cors: true
